services:
  - type: web
    name: nivaaran-backend
    env: node
    rootDirectory: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 4000
